import { Header } from "@/shared/components/shared/header";

export const metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by create next app',
}

export default function CheckoutLayout({ children } : { children: React.ReactNode }) {
  return (

    <main className="min-h-screen bg-[#F4F1EE]">
      <Header hasSeaarch={false} className="border-gray-200" />
      {children}
    </main>
  )
}